# Generated by Django 4.1.7 on 2023-11-15 13:06

import apps.profilee.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profiles_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('fio', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[apps.profilee.models.validate_phone_number])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
            ],
        ),
    ]
